apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project2
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/celeguim/gitops.git
  destinations:
  - server: https://kubernetes.default.svc
    namespace: prod
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
