apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: proj1
  namespace: argocd
spec:
  sourceRepos:
  - xxxxxxxxxxxxxxxxxxx
  destinations:
  - server: adsfdsafdsa
    namespace: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
