apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: gitops1
        path: charts/microservice
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/celeguim/gitops.git
        path: '{{path}}'
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: default
