apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
spec:
  project: project1
  source:
    repoURL: https://github.com/celeguim/gitops.git
    path: charts/nginx
    targetRevision: target1
  destination:
    server: local.k8s.svc
    namespace: app1
