apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/example/repo.git
    path: charts/app2
    targetRevision: HEAD
  destination:
    server: adsfdsafdsa
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
